# Part 1: Intro to PyTorch

In this module, we will learn some basic computations of PyTorch.

## 1.0 Install PyTorch

In [1]:
# I have installed PyTorch through my terminal in my virtual environment
# For detailed information on how to install PyTorch, please refer to:
# https://pytorch.org/get-started/locally/

In [2]:
# Importing libraries
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn

## 1.1 What is PyTorch ?
- PyTorch is a machine learning library.
- It provides functions for creating and mainpulating tensors.
- Tensors - data structures which are multi-dimensional arrays. They can be described as n-dimensional arrays of base datatypes like integers, floats and strings.
- It provides ability to perform computations on tensors, define neural networks and train them.

### Shape of a tensor: 
defines number of dimensions and size of each dimension.

In [3]:
# examples of tensors
integer = torch.tensor(9923)
decimal = torch.tensor(3.14)

# printing tensors and their dimensions
print(f"`integer` is a tensor of dimension {integer.ndim}")
print(f"`decimal` is a tensor of dimension {decimal.ndim}")

`integer` is a tensor of dimension 0
`decimal` is a tensor of dimension 0


Tensors of dimension 1 can be created using lists or vectors

In [4]:
sequence = torch.tensor(range(100))
print(f"`sequence` is a tensor of dimension {sequence.ndim} and shape: {sequence.shape}")

`sequence` is a tensor of dimension 1 and shape: torch.Size([100])


Tensors of higer dimensions:

In [5]:
# 2d tensors
matrix_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
# Assertions to check the properties of the tensors
assert isinstance(matrix_2d, torch.Tensor), "matrix_2d is not a tensor"
assert matrix_2d.ndim == 2

print(f"`matrix_2d` is a tensor of dimension {matrix_2d.ndim} and shape: {matrix_2d.shape}")

# 3d tensors
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

assert isinstance(tensor_3d, torch.Tensor), "tensor_3d is not a tensor"
assert tensor_3d.ndim == 3
print(f"`tensor_3d` is a tensor of dimension {tensor_3d.ndim} and shape: {tensor_3d.shape}")

`matrix_2d` is a tensor of dimension 2 and shape: torch.Size([2, 3])
`tensor_3d` is a tensor of dimension 3 and shape: torch.Size([2, 2, 2])



3d tensors can be visualized as a stack of matrices or a cube of numbers<br>
These are generally used to represent images, videos, etc.

In [6]:
# define a 4d tensor
tensor_4d = torch.tensor([[[[1,2],[3,4],[5,6],[7,8]],[[1,2],[3,4],[5,6],[7,8]]],
                          [[[1,2],[3,4],[5,6],[7,8]],[[1,2],[3,4],[5,6],[7,8]]]])

assert isinstance(tensor_4d, torch.Tensor), "tensor_4d is not a tensor"
assert tensor_4d.ndim == 4, "tensor_4d is not a 4-dimensional tensor"
print(f"`tensor_4d` is a tensor of dimension {tensor_4d.ndim} and shape: {tensor_4d.shape}")

`tensor_4d` is a tensor of dimension 4 and shape: torch.Size([2, 2, 4, 2])


Use torch.zeros to initialize a 4-d Tensor of zeros with size 10 x 3 x 256 x 256.<br>
Breakdown: 10 images, RGB, 256x256

In [7]:
# initializing 4-d tensor of images
images = torch.tensor([
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])]
                    
                    ])

assert isinstance(images, torch.Tensor), "images is not a tensor"
assert images.ndim == 4, "images is not a 4-dimensional tensor"
assert images.shape == (10, 3, 256, 256), "images does not have the expected shape"
print(f"`images` is a {images.ndim}-d Tensor with shape: {images.shape}")

# That's probably the dumbest way to initialize a 4-d Tensor of zeros with size 10 x 3 x 256 x 256.

# A better way to do this is:
images = torch.zeros(10, 3, 256, 256)
# display(images)

assert isinstance(images, torch.Tensor), "images is not a tensor"
assert images.ndim == 4, "images is not a 4-dimensional tensor"
assert images.shape == (10, 3, 256, 256), "images does not have the expected shape"
print(f"`images` is a {images.ndim}-d Tensor with shape: {images.shape}")

`images` is a 4-d Tensor with shape: torch.Size([10, 3, 256, 256])
`images` is a 4-d Tensor with shape: torch.Size([10, 3, 256, 256])


/tmp/ipykernel_3174/442107092.py:2: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:254.)
  images = torch.tensor([


Slicing can be used to access subtensors.

In [8]:
# using slicing to access subtensors from a 2d tensor
print("2d Tensor:")
display(matrix_2d)

subtensor_2d = matrix_2d[0:2, 1:3]

print("Subtensor from 2d Tensor:")
display(subtensor_2d)

print("Row Vector from 2d Tensor:")
row_vector_2d = matrix_2d[0]
display(row_vector_2d)

print("Column Vector from 2d Tensor:")
column_vector_2d = matrix_2d[:, 0]
display(column_vector_2d)

print("Scalar from 2d Tensor:")
scalar_2d = matrix_2d[0, 1]
display(scalar_2d)

2d Tensor:


tensor([[1, 2, 3],
        [4, 5, 6]])

Subtensor from 2d Tensor:


tensor([[2, 3],
        [5, 6]])

Row Vector from 2d Tensor:


tensor([1, 2, 3])

Column Vector from 2d Tensor:


tensor([1, 4])

Scalar from 2d Tensor:


tensor(2)

## 1.2 Computation on Tensors

Computation on tensors can be visualized using graphs. These graphs hold data and mathematical operations that act on the tensors in a specific order.<br>
A simple example is illustrated in the graph below:<br><br>
![alt text](tensor_computation_1.svg)

In [13]:
# create nodes of the graph 
a = torch.tensor(20)
b = torch.tensor(32)

# perform addition operation
c1 = torch.add(a, b)
c2 = a + b

# print(f"c1: {c1}, c2: {c2}")
print(f"c1: {c1} is a tensor ? {isinstance(c1, torch.Tensor)}")
print(f"c2: {c2} is a tensor ? {isinstance(c2, torch.Tensor)}")

c1: 52 is a tensor ? True
c2: 52 is a tensor ? True


Considering a slightly more complicated example:<br><br>
![alt text](tensor_computation_2.svg)

In [14]:
# defining a function to perform computation as shown in the graph
def compute(a, b):
    c = torch.add(a, b)
    d = torch.subtract(b, 1)
    e = torch.multiply(c, d)
    return e

In [16]:
# use the function to perform computation
result = compute(a, b)
print(f"Computation done on a: {a} and b: {b} resulted in : {result}")
print(f"Result is a tensor ? {isinstance(result, torch.Tensor)}")

Computation done on a: 20 and b: 32 resulted in : 1612
Result is a tensor ? True


## 1.3 Neural Networks in PyTorch

We can define neural networks in PyTorch. Well that's the dominant use case of PyTorch!<br>
PyTorch uses <mark>torch.nn.Module</mark> - it serves as base class for all neural network modules in PyTorch - providing framework to build and train these neural networks.<br>

Below is a graphical representation of a simple neural network:<br><br>
![alt text](simple_neural_network.svg)

We use <mark>torch.nn.Module</mark> to define the layers, which contain groups of perceptrons(neurons), the building blocks of neural networks.<br>
To implement a layer, we subclass <mark>torch.nn.Module</mark> and define parameters of layers (w,x,b) as attributes of this new class.<br>
It is also necessary to overload <mark>forward</mark> function by defining a forward computation function performed at every step.<br>
<br>
Writing a dense layer for the network shown above:

In [ ]:
# defining a new layer

# num_inputs: number of input nodes
# num_outputs: number of output nodes
# x: input tensor

class DenseLayer(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super(DenseLayer,self).__init__()

        # defining the parameters of the layer and initializing them randomly
        self.W = torch.nn.Parameter(torch.randn(num_inputs, num_outputs))
        self.b = torch.nn.Parameter(torch.randn(num_outputs))

    # defining the forward computation function (override)
    def forward(self, x):
        # operation for z
        z = self.b + torch.matmul(x,self.W)

        # apply activation function
        y = torch.sigmoid(z)
        return y

Testing the output of the layer defined...

In [32]:
# define number of input and output nodes
num_inputs = 2
num_outputs = 3

# define the layer
layer = DenseLayer(num_inputs, num_outputs)
x_input = torch.tensor([[1.0, 3.0]])

# display(x_input.shape)

y = layer(x_input)

print("Done defining the layer!\n")
print(f"Input shape: {x_input.shape}")
print(f"Output shape: {y.shape}")
print(f"Outputs from the layer: {y}")

Done defining the layer!

Input shape: torch.Size([1, 2])
Output shape: torch.Size([1, 3])
Outputs from the layer: tensor([[0.9990, 0.5357, 0.9686]], grad_fn=<SigmoidBackward0>)


PyTorch has predefined nn.Modules (Layers) which are commonly used,like, <mark>nn.linear</mark> or <mark>nn.Sigmoid</mark>.<br>
Instead of nn.Module to define a network, we can use <mark>nn.Sequential</mark> module and a single <mark>nn.Linear</mark> layer.<br>
<b>Sequential API</b> can be used to build networks by stacking multiple layers.

In [54]:
# Using Sequential API to build a neural network

# define number of input and output nodes
ip_nodes = 2
op_nodes = 3

# defining the model using Sequential API
model = nn.Sequential(
    nn.Linear(ip_nodes,op_nodes),
    nn.Sigmoid()
)

Testing the model with example inputs...

In [57]:
model_output = model(x_input)

print(f"Input Shape: {x_input.shape}")
print(f"Output Shape: {model_output.shape}")
print(f"Output from the network: {model_output}")

Input Shape: torch.Size([1, 2])
Output Shape: torch.Size([1, 3])
Output from the network: tensor([[0.2088, 0.6832, 0.1631]], grad_fn=<SigmoidBackward0>)
