# Part 1: Intro to PyTorch

In this module, we will learn some basic computations of PyTorch.

## 1.0 Install PyTorch

In [6]:
# I have installed PyTorch through my terminal in my virtual environment
# For detailed information on how to install PyTorch, please refer to:
# https://pytorch.org/get-started/locally/

In [7]:
# Importing libraries
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn

## 1.1 What is PyTorch ?
- PyTorch is a machine learning library.
- It provides functions for creating and mainpulating tensors.
- Tensors - data structures which are multi-dimensional arrays. They can be described as n-dimensional arrays of base datatypes like integers, floats and strings.
- It provides ability to perform computations on tensors, define neural networks and train them.

### Shape of a tensor: 
defines number of dimensions and size of each dimension.

In [10]:
# examples of tensors
integer = torch.tensor(9923)
decimal = torch.tensor(3.14)

# printing tensors and their dimensions
print(f"`integer` is a tensor of dimension {integer.ndim}")
print(f"`decimal` is a tensor of dimension {decimal.ndim}")

`integer` is a tensor of dimension 0
`decimal` is a tensor of dimension 0


Tensors of dimension 1 can be created using lists or vectors

In [15]:
sequence = torch.tensor(range(100))
print(f"`sequence` is a tensor of dimension {sequence.ndim} and shape: {sequence.shape}")

`sequence` is a tensor of dimension 1 and shape: torch.Size([100])


Tensors of higer dimensions:

In [39]:
# 2d tensors
matrix_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
# Assertions to check the properties of the tensors
assert isinstance(matrix_2d, torch.Tensor), "matrix_2d is not a tensor"
assert matrix_2d.ndim == 2

print(f"`matrix_2d` is a tensor of dimension {matrix_2d.ndim} and shape: {matrix_2d.shape}")

# 3d tensors
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

assert isinstance(tensor_3d, torch.Tensor), "tensor_3d is not a tensor"
assert tensor_3d.ndim == 3
print(f"`tensor_3d` is a tensor of dimension {tensor_3d.ndim} and shape: {tensor_3d.shape}")

`matrix_2d` is a tensor of dimension 2 and shape: torch.Size([2, 3])
`tensor_3d` is a tensor of dimension 3 and shape: torch.Size([2, 2, 2])



3d tensors can be visualized as a stack of matrices or a cube of numbers<br>
These are generally used to represent images, videos, etc.

In [40]:
# define a 4d tensor
tensor_4d = torch.tensor([[[[1,2],[3,4],[5,6],[7,8]],[[1,2],[3,4],[5,6],[7,8]]],
                          [[[1,2],[3,4],[5,6],[7,8]],[[1,2],[3,4],[5,6],[7,8]]]])

assert isinstance(tensor_4d, torch.Tensor), "tensor_4d is not a tensor"
assert tensor_4d.ndim == 4, "tensor_4d is not a 4-dimensional tensor"
print(f"`tensor_4d` is a tensor of dimension {tensor_4d.ndim} and shape: {tensor_4d.shape}")

`tensor_4d` is a tensor of dimension 4 and shape: torch.Size([2, 2, 4, 2])


Use torch.zeros to initialize a 4-d Tensor of zeros with size 10 x 3 x 256 x 256.<br>
Breakdown: 10 images, RGB, 256x256

In [56]:
# initializing 4-d tensor of images
images = torch.tensor([
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])],
                    [np.zeros([256,256]),np.zeros([256,256]),np.zeros([256,256])]
                    
                    ])

assert isinstance(images, torch.Tensor), "images is not a tensor"
assert images.ndim == 4, "images is not a 4-dimensional tensor"
assert images.shape == (10, 3, 256, 256), "images does not have the expected shape"
print(f"`images` is a {images.ndim}-d Tensor with shape: {images.shape}")

# That's probably the dumbest way to initialize a 4-d Tensor of zeros with size 10 x 3 x 256 x 256.

# A better way to do this is:
images = torch.zeros(10, 3, 256, 256)
# display(images)

assert isinstance(images, torch.Tensor), "images is not a tensor"
assert images.ndim == 4, "images is not a 4-dimensional tensor"
assert images.shape == (10, 3, 256, 256), "images does not have the expected shape"
print(f"`images` is a {images.ndim}-d Tensor with shape: {images.shape}")

`images` is a 4-d Tensor with shape: torch.Size([10, 3, 256, 256])
`images` is a 4-d Tensor with shape: torch.Size([10, 3, 256, 256])


Slicing can be used to access subtensors.

In [64]:
# using slicing to access subtensors from a 2d tensor
print("2d Tensor:")
display(matrix_2d)

subtensor_2d = matrix_2d[0:2, 1:3]

print("Subtensor from 2d Tensor:")
display(subtensor_2d)

print("Row Vector from 2d Tensor:")
row_vector_2d = matrix_2d[0]
display(row_vector_2d)

print("Column Vector from 2d Tensor:")
column_vector_2d = matrix_2d[:, 0]
display(column_vector_2d)

print("Scalar from 2d Tensor:")
scalar_2d = matrix_2d[0, 1]
display(scalar_2d)

2d Tensor:


tensor([[1, 2, 3],
        [4, 5, 6]])

Subtensor from 2d Tensor:


tensor([[2, 3],
        [5, 6]])

Row Vector from 2d Tensor:


tensor([1, 2, 3])

Column Vector from 2d Tensor:


tensor([1, 4])

Scalar from 2d Tensor:


tensor(2)

## 1.2 Computation on Tensors